name: ESPLEDs CI 

on: [push, pull_request]

jobs:
  unittests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run Tests
      run: make test

  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: arduino/compile-sketches@v1
      with:
        platforms: |
          - name: esp32:esp32
            source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
        sketch-paths: |
          - ./
        fqbn: "esp32:esp32:esp32"
        enable-deltas-report: true
        libraries: |
          - name: "Adafruit NeoPixel"
            source-url: https://github.com/adafruit/Adafruit_NeoPixel.git
            version: 1.10.0
          - name: "Arduino JSON"
            source-url: https://github.com/bblanchon/ArduinoJson.git
            version: 1.10.0
    - uses: actions/upload-artifact@v2
      with:
        name: sketches-reports
        path: sketches-reports

  report:
    needs: compile 
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Download sketches reports artifact
        uses: actions/download-artifact@v2

      - uses: arduino/report-size-deltas@v1
